Repository cool-fe/winex-cli, pull requests merged in 2021-05, with the labels that each got.

#2 feat: add init plugin
  packages/cli-plugin-add/package.json
  packages/cli-plugin-init/.fatherrc.ts
  packages/cli-plugin-init/CHANGELOG.md
  packages/cli-plugin-init/package.json
  packages/cli-plugin-init/src/GenerateTemplate.ts
  packages/cli-plugin-init/src/PackageManager.ts
  packages/cli-plugin-init/src/commands.ts
  packages/cli-plugin-init/src/constants/businessType.ts
  packages/cli-plugin-init/src/constants/group.ts
  packages/cli-plugin-init/src/constants/index.ts
  packages/cli-plugin-init/src/constants/projectType.ts
  packages/cli-plugin-init/src/constants/registries.ts
  packages/cli-plugin-init/src/generateTemplate.ts
  packages/cli-plugin-init/src/index.ts
  packages/cli-plugin-init/src/interface/command.ts
  packages/cli-plugin-init/src/interface/file.ts
  packages/cli-plugin-init/src/interface/index.ts
  packages/cli-plugin-init/src/interface/package.ts
  packages/cli-plugin-init/src/interface/prompt.ts
  packages/cli-plugin-init/src/packageManager.ts
  packages/cli-plugin-init/src/prompts/project.ts
  packages/cli-plugin-init/src/utils/clearConsole.ts
  packages/cli-plugin-init/src/utils/excuteCommand.ts
  packages/cli-plugin-init/src/utils/file.ts
  packages/cli-plugin-init/src/utils/getGitInfo.ts
  packages/cli-plugin-init/src/utils/getNpmPkg.ts
  packages/cli-plugin-init/src/utils/index.ts
  packages/cli-plugin-init/src/utils/loadRemotePreset.ts
  packages/cli-plugin-init/src/utils/package.ts
  packages/cli-plugin-init/src/utils/renameConfigFiles.ts
  packages/cli/src/index.ts
  yarn.lock
Labels: enhancement

#15 Fix：修复0521发现的bug
  packages/cli-plugin-lint/src/add-editor-config.ts
  packages/cli-plugin-lint/src/add-prettier-config.ts
  packages/cli-plugin-lint/src/config.ts
  packages/cli-plugin-lint/src/index.ts
  packages/cli-plugin-lint/src/install-config.ts
  packages/cli-plugin-lint/src/utils/npm-utils.ts
Labels: bug, documentation, enhancement

#37 feat: feat pr test
  package.json
Labels: feat

#47 feat: 规范物料的指定版本，完善使用文档
  packages/cli-plugin-add/README.md
  packages/cli-plugin-add/src/index.ts
  packages/cli-plugin-add/src/interface/index.ts
  packages/cli-plugin-add/src/utils/GetMaterial.ts
  packages/cli-plugin-add/src/utils/syncInstallDeps.ts
Labels: enhancement

#49 fix: 缩减日志 & 安装husky进行错误拦截
  packages/cli-plugin-lint/src/add-prettier-config.ts
  packages/cli-plugin-lint/src/ci.ts
  packages/cli-plugin-lint/src/deps-install.ts
  packages/cli-plugin-lint/src/install-config.ts
  packages/cli-plugin-lint/src/utils/config-file.ts
Labels: enhancement, feat
